# Generated by Django 5.0.7 on 2025-04-07 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('total_animals', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cash_entries',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_batch_no', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('expiry_days', models.IntegerField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'member_account_types',
            },
        ),
        migrations.CreateModel(
            name='OffalCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'offal_collectors',
            },
        ),
        migrations.CreateModel(
            name='Tannery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('prints_counter', models.IntegerField(blank=True, null=True)),
                ('cash_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welc.cashentry')),
            ],
            options={
                'db_table': 'confirmations',
            },
        ),
        migrations.CreateModel(
            name='Hd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_date', models.DateTimeField(blank=True, null=True)),
                ('animal_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('tag_id', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Supplier_id', models.CharField(blank=True, max_length=50, null=True)),
                ('animal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('slaughter_date', models.DateField(blank=True, null=True)),
                ('leather_type', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_to', models.CharField(blank=True, max_length=255, null=True)),
                ('hide_source', models.CharField(blank=True, choices=[('Buffalo', 'Buffalo'), ('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Goat', 'Goat')], max_length=20, null=True)),
                ('tannery_stamp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_types', models.CharField(blank=True, max_length=200, null=True)),
                ('other_product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('trader_arrived', models.DateTimeField(blank=True, null=True)),
                ('trader_dispatched', models.DateTimeField(blank=True, null=True)),
                ('tannery_arrived', models.DateTimeField(blank=True, null=True)),
                ('tannery_dispatched', models.DateTimeField(blank=True, null=True)),
                ('garment_arrived', models.DateTimeField(blank=True, null=True)),
                ('garment_dispatched', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tag_data',
            },
        ),
        migrations.AddField(
            model_name='cashentry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welc.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welc.memberaccounttype'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='offal_collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welc.offalcollector'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('day_counter', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welc.confirmation')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagGeneration',
            fields=[
                ('new_tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('old_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_no', models.CharField(max_length=50)),
                ('total_animals', models.IntegerField()),
                ('command', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_name', models.CharField(max_length=255)),
                ('expiry_days', models.IntegerField()),
                ('account_type', models.CharField(max_length=50)),
                ('offal_collector', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_code', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tags', models.IntegerField()),
                ('total_prints', models.IntegerField()),
                ('print_count', models.IntegerField(default=0)),
                ('hide_source', models.CharField(blank=True, choices=[('Buffalo', 'Buffalo'), ('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Goat', 'Goat')], max_length=20, null=True)),
                ('tannery_stamp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_to', models.CharField(blank=True, max_length=255, null=True)),
                ('g_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('product_types', models.CharField(blank=True, max_length=200, null=True)),
                ('other_product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('trader_arrived', models.DateTimeField(blank=True, null=True)),
                ('trader_dispatched', models.DateTimeField(blank=True, null=True)),
                ('tannery_arrived', models.DateTimeField(blank=True, null=True)),
                ('tannery_dispatched', models.DateTimeField(blank=True, null=True)),
                ('garment_arrived', models.DateTimeField(blank=True, null=True)),
                ('garment_dispatched', models.DateTimeField(blank=True, null=True)),
                ('traders', models.ManyToManyField(blank=True, related_name='trader_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tannery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hides', to='welc.tannery')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('arrived', 'Arrived'), ('dispatched', 'Dispatched'), ('data_entered', 'Data Entered')], max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('actor_type', models.CharField(max_length=20)),
                ('new_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='welc.taggeneration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
