# Generated by Django 5.0.7 on 2025-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeneration',
            name='g_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
