# Generated by Django 5.0.7 on 2025-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0002_alter_taggeneration_g_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeneration',
            name='garment_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
