# Generated by Django 5.0.7 on 2025-04-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0003_taggeneration_garment_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeneration',
            name='garment_tag',
        ),
    ]
