# Generated by Django 5.0.7 on 2025-04-20 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0004_remove_taggeneration_garment_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentProduct',
            fields=[
                ('garment_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('num_pieces', models.PositiveIntegerField()),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_types', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('other_product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('g_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='welc.taggeneration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taggeneration',
            name='garment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welc.garmentproduct'),
        ),
    ]
