# Generated by Django 5.0.7 on 2025-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0005_garmentproduct_taggeneration_garment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='tags',
            field=models.ManyToManyField(related_name='garment_products', to='welc.taggeneration'),
        ),
    ]
