# Generated by Django 5.0.7 on 2025-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0006_alter_garmentproduct_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='dispatch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='garmentproduct',
            name='tags',
            field=models.ManyToManyField(help_text='Leather tags used in this garment product', related_name='garment_products', to='welc.taggeneration'),
        ),
    ]
