# Generated by Django 5.0.7 on 2025-04-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0007_alter_garmentproduct_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='garment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='welc.garmentproduct'),
        ),
    ]
