# Generated by Django 5.0.7 on 2025-04-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0008_transactionlog_garment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeneration',
            name='garment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='welc.garmentproduct'),
        ),
    ]
