# Generated by Django 5.0.7 on 2025-04-21 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0009_alter_taggeneration_garment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='garment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_tags', to='welc.garmentproduct'),
        ),
    ]
