# Generated by Django 5.0.7 on 2025-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0010_taggeneration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='g_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
