# Generated by Django 5.0.7 on 2025-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0011_alter_garmentproduct_g_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='g_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
