# Generated by Django 5.0.7 on 2025-04-22 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0012_alter_garmentproduct_g_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taggeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('garment_product__isnull', False)), fields=('new_tag', 'garment_product'), name='unique_tag_garment'),
        ),
    ]
