# Generated by Django 5.0.7 on 2025-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0013_taggeneration_unique_tag_garment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='dispatch_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Server-recorded dispatch time', null=True),
        ),
        migrations.AlterField(
            model_name='garmentproduct',
            name='g_date',
            field=models.DateTimeField(blank=True, help_text='User-specified process date/time', null=True, verbose_name='Process Date'),
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='g_date',
            field=models.DateTimeField(blank=True, help_text='Process date from garment product', null=True),
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='garment_dispatched',
            field=models.DateTimeField(blank=True, help_text='Actual server time of dispatch', null=True),
        ),
    ]
