# Generated by Django 5.0.7 on 2025-04-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0014_alter_garmentproduct_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='garment_dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
