# Generated by Django 5.0.7 on 2025-04-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0015_alter_garmentproduct_dispatch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentproduct',
            name='tags',
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='garment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='welc.garmentproduct'),
        ),
    ]
