# Generated by Django 5.0.7 on 2025-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0016_remove_garmentproduct_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentproduct',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taggeneration',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
