# Generated by Django 5.0.7 on 2025-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0017_garmentproduct_time_stamp_taggeneration_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentproduct',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taggeneration',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
