# Generated by Django 5.0.7 on 2025-04-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0018_alter_garmentproduct_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='tannery_stamp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
