# Generated by Django 5.0.7 on 2025-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0019_transactionlog_tannery_stamp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hd',
            name='trader_name',
        ),
    ]
