# Generated by Django 5.0.7 on 2025-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0020_remove_hd_trader_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeneration',
            name='product_types',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
