# Generated by Django 5.0.7 on 2025-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0021_alter_taggeneration_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeneration',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taggeneration',
            name='tannage_type',
            field=models.CharField(blank=True, choices=[('Chrome', 'Chrome'), ('Chrome-free', 'Chrome-free'), ('Vegetable', 'Vegetable')], max_length=20, null=True),
        ),
    ]
