# Generated by Django 5.0.7 on 2025-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welc', '0022_taggeneration_article_taggeneration_tannage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
