# Generated by Django 5.0.7 on 2025-04-07 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('slaughterhouse', 'Slaughterhouse'), ('trader', 'Trader'), ('tannery', 'Tannery'), ('garment', 'Garment')], max_length=20, null=True)),
                ('brand', models.CharField(blank=True, default='PAMCO', max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('leather_types', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('animal_types', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='Unknown', max_length=200, null=True)),
                ('operation_type', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
