# Generated by Django 5.0.7 on 2025-04-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.CharField(blank=True, help_text='Comma-separated list of certifications', max_length=255, null=True),
        ),
    ]
