# Generated by Django 5.0.7 on 2025-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_profile_animal_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brand',
            field=models.CharField(blank=True, default='PAMCO', max_length=100, null=True),
        ),
    ]
