# Generated by Django 5.0.7 on 2025-04-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_profile_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brand',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
