# Generated by Django 5.0.7 on 2025-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_brand'),
        ('myapp', '0003_profile_brand'),
    ]

    operations = [
    ]
