# Generated by Django 5.0.7 on 2025-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_time_stamp_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
