# Generated by Django 5.0.7 on 2025-04-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_0003_alter_profile_brand_0003_profile_brand'),
        ('myapp', '0005_remove_profile_updated_at_alter_profile_time_stamp'),
    ]

    operations = [
    ]
