# Generated by Django 5.0.7 on 2025-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20250429_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brand',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
