# Generated by Django 5.0.7 on 2025-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='animal_types',
            field=models.CharField(blank=True, help_text='Comma-separated animal types', max_length=255, null=True),
        ),
    ]
