# Generated by Django 5.0.7 on 2025-04-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_profile_animal_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leather_types',
            field=models.CharField(blank=True, help_text='Comma-separated leather types', max_length=255, null=True),
        ),
    ]
