# Generated by Django 5.0.7 on 2025-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('slaughterhouse', 'Slaughterhouse'), ('trader', 'Trader'), ('tannery', 'Tannery'), ('garment', 'Garment'), ('visitor', 'Visitor')], max_length=20, null=True),
        ),
    ]
