# Generated by Django 5.0.7 on 2025-07-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_profile_contact'),
        ('myapp', '0011_alter_profile_role'),
    ]

    operations = [
    ]
