# Generated by Django 5.0.7 on 2025-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_profile_unique_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
