# Generated by Django 5.0.7 on 2025-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_profile_contact_person_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('slaughterhouse', 'Slaughterhouse'), ('trader', 'Trader'), ('tannery', 'Tannery'), ('garment', 'Garment'), ('visitor', 'Visitor'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
